const runtimes = [
    { "language": "bash", "version": "5.2.0", "extension": ".sh" },
    { "language": "clojure", "version": "1.10.3", "extension": ".clj" },
    { "language": "coffeescript", "version": "2.5.1", "extension": ".coffee" },
    { "language": "crystal", "version": "0.36.1", "extension": ".cr" },
    { "language": "dart", "version": "2.19.6", "extension": ".dart" },
    { "language": "typescript", "version": "5.0.3", "extension": ".ts" },
    { "language": "javascript", "version": "18.15.0", "extension": ".js" },
    { "language": "elixir", "version": "1.11.3", "extension": ".ex" },
    { "language": "emacs", "version": "27.1.0", "extension": ".el" },
    { "language": "erlang", "version": "23.0.0", "extension": ".erl" },
    { "language": "c", "version": "10.2.0", "extension": ".c" },
    { "language": "cplusplus", "version": "10.2.0", "extension": ".cpp" },
    { "language": "fortran", "version": "10.2.0", "extension": ".f90" },
    { "language": "go", "version": "1.16.2", "extension": ".go" },
    { "language": "groovy", "version": "3.0.7", "extension": ".groovy" },
    { "language": "haskell", "version": "9.0.1", "extension": ".hs" },
    { "language": "java", "version": "15.0.2", "extension": ".java" },
    { "language": "julia", "version": "1.8.5", "extension": ".jl" },
    { "language": "kotlin", "version": "1.8.20", "extension": ".kt" },
    { "language": "lua", "version": "5.4.4", "extension": ".lua" },
    { "language": "csharp", "version": "6.12.0", "extension": ".cs" },
    { "language": "nim", "version": "1.6.2", "extension": ".nim" },
    { "language": "ocaml", "version": "4.12.0", "extension": ".ml" },
    { "language": "perl", "version": "5.36.0", "extension": ".pl" },
    { "language": "php", "version": "8.2.3", "extension": ".php" },
    { "language": "prolog", "version": "8.2.4", "extension": ".pl" },
    { "language": "powershell", "version": "7.1.4", "extension": ".ps1" },
    { "language": "python", "version": "3.10.0", "extension": ".py" },
    { "language": "ruby", "version": "3.0.1", "extension": ".rb" },
    { "language": "rust", "version": "1.68.2", "extension": ".rs" },
    { "language": "scala", "version": "3.2.2", "extension": ".scala" },
    { "language": "swift", "version": "5.3.3", "extension": ".swift" },
    { "language": "zig", "version": "0.10.1", "extension": ".zig" }
  ];

export {runtimes}